name: Semantic Versioning and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # - name: Install dependencies
      #   run: npm install
      #   working-directory: ./path/to/your/package

      # - name: Determine version bump
      #   id: determine_bump
      #   run: |
      #     COMMIT_MSG=$(git log --format=%B -n 1 HEAD)
      #     if [[ $COMMIT_MSG == *"[major]"* ]]; then
      #       echo "major"
      #     elif [[ $COMMIT_MSG == *"[minor]"* ]]; then
      #       echo "minor"
      #     else
      #       echo "patch"
      #     fi
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

      # - name: Bump version
      #   run: |
      #     BUMP_TYPE=$(echo "${{ steps.determine_bump.outputs.stdout }}")
      #     npm version $BUMP_TYPE -m "Bump version to %s"
      #   working-directory: ./path/to/your/package

      - name: Push changes
        run: |
          git push origin HEAD:${{ env.DEFAULT_BRANCH }}
        working-directory: ./path/to/your/package
