name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get last commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 HEAD)"

      - name: Determine version bump
        id: version_bump
        run: |
          COMMIT_MESSAGE=$(echo "${{ steps.commit_message.outputs.message }}")
          if [[ "$COMMIT_MESSAGE" =~ ^feat ]]; then
            echo "::set-output name=bump::patch"
          elif [[ "$COMMIT_MESSAGE" =~ ^fix ]]; then
            echo "::set-output name=bump::patch"
          elif [[ "$COMMIT_MESSAGE" =~ ^perf ]]; then
            echo "::set-output name=bump::patch"
          elif [[ "$COMMIT_MESSAGE" =~ ^docs ]]; then
            echo "::set-output name=bump::patch"
          elif [[ "$COMMIT_MESSAGE" =~ ^style ]]; then
            echo "::set-output name=bump::patch"
          elif [[ "$COMMIT_MESSAGE" =~ ^refactor ]]; then
            echo "::set-output name=bump::patch"
          elif [[ "$COMMIT_MESSAGE" =~ ^test ]]; then
            echo "::set-output name=bump::patch"
          elif [[ "$COMMIT_MESSAGE" =~ ^build ]]; then
            echo "::set-output name=bump::patch"
          elif [[ "$COMMIT_MESSAGE" =~ ^ci ]]; then
            echo "::set-output name=bump::patch"
          elif [[ "$COMMIT_MESSAGE" =~ ^chore ]]; then
            echo "::set-output name=bump::patch"
          else
            echo "::set-output name=bump::none"
          fi

      - name: Bump version
        id: version
        uses: anothrNick/github-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
          tags: true
          bump: ${{ steps.version_bump.outputs.bump }}

      - name: Set output version
        run: echo "VERSION=${{ steps.version.outputs.new_tag }}" >> $GITHUB_ENV

