name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to use Node.js 20

      - name: Get last commit message
        id: commit_message
        run: echo "$(git log --format=%B -n 1 HEAD)" >> commit_message.txt

      - name: Determine version bump
        id: version_bump
        run: |
          COMMIT_MESSAGE=$(cat commit_message.txt)
          if [[ "$COMMIT_MESSAGE" =~ ^feat ]]; then
            echo "minor" >> version_bump.txt
          elif [[ "$COMMIT_MESSAGE" =~ ^fix|perf|docs|style|refactor|test|build|ci|chore ]]; then
            echo "patch" >> version_bump.txt
          else
            echo "none" >> version_bump.txt
          fi

      - name: Display version bump
        run: echo "Version bump detected:$(cat version_bump.txt)"

      - name: Read version bump
        id: read_version_bump
        run: |
          VERSION_BUMP=$(cat version_bump.txt)
          echo "VERSION_BUMP=${VERSION_BUMP//$'\n'/ }" >> $GITHUB_ENV

      - name: Bump version to minor
        if: ${{ steps.read_version_bump.outputs.VERSION_BUMP == 'minor' }}
        uses: anothrNick/github-tag-action@v1  # Updated action version
        with:
          tag_name: v${{ steps.read_version_bump.outputs.VERSION_BUMP }}
          tag_prefix: v  # Consistent prefix
          token: ${{ secrets.GITHUB_TOKEN }}  # Access token secured

      - name: Bump version to patch
        if: ${{ steps.read_version_bump.outputs.VERSION_BUMP == 'patch' }}
        uses: anothrNick/github-tag-action@v1  # Updated action version
        with:
          tag_name: v${{ steps.read_version_bump.outputs.VERSION_BUMP }}
          tag_prefix: v  # Consistent prefix
          token: ${{ secrets.GITHUB_TOKEN }}  # Access token secured

      - name: Bump version to default
        if: ${{ steps.read_version_bump.outputs.VERSION_BUMP == 'none' }}
        uses: anothrNick/github-tag-action@v1  # Updated action version
        with:
          tag_name: v0.0.1
          tag_prefix: v  # Consistent prefix
          token: ${{ secrets.GITHUB_TOKEN }}  # Access token secured

  release-drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
