name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Improved checkout action version

      - name: Get last commit message
        id: commit_message
        run: echo "$(git log --format=%B -n 1 HEAD)" >> commit_message.txt

      - name: Determine version bump
        id: version_bump
        run: |
          COMMIT_MESSAGE=$(cat commit_message.txt)
          if [[ "$COMMIT_MESSAGE" =~ ^feat ]]; then
            echo "minor" >> version_bump.txt
          elif [[ "$COMMIT_MESSAGE" =~ ^fix|perf|docs|style|refactor|test|build|ci|chore ]]; then
            echo "patch" >> version_bump.txt
          else
            echo "none" >> version_bump.txt
          fi

      - name: Read version bump
        id: read_version_bump
        run: |
          VERSION_BUMP=$(cat version_bump.txt)
          echo "VERSION_BUMP=${VERSION_BUMP//$'\n'/ }" >> $GITHUB_ENV

      - name: Bump version (with proper inputs)
        uses: anothrNick/github-tag-action@v1.2  # Updated action version
        with:
          tag_name: ${{ steps.read_version_bump.outputs.VERSION_BUMP == 'none' ? 'v0.0.1' : format('{0}.{1}.{2}', steps.version.outputs.major_version, steps.version.outputs.minor_version, steps.version.outputs.patch_version) }}  # Conditional tag creation with default
          tag_prefix: v  # Consistent prefix
          token: ${{ secrets.GITHUB_TOKEN }}  # Access token secured

