name: Auto Tag my Application

on:
  push:
    branches:
      - main

concurrency:
  production

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Get next tag version (dry run)
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true

      - name: Display next tag version
        run: |
          echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"

      - name: Display current tag
        run: |
          echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"

      - name: Display version increment
        run: |
          echo "The version increment was: ${{ steps.taggerDryRun.outputs.part }}"

      # DO MY BUILD HERE
      # IN CASE OF FAILURE, THE STEP BELOW WILL NOT RUN.

      - name: Tag the final version
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

# Environment files to set outputs
env:
  NEXT_TAG_VERSION: ${{ steps.taggerDryRun.outputs.new_tag }}
  CURRENT_TAG_VERSION: ${{ steps.taggerDryRun.outputs.tag }}
  VERSION_INCREMENT: ${{ steps.taggerDryRun.outputs.part }}
