name: Semantic Versioning and Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install || yarn install

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Semantic Release
        uses: semantic-release/action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate build metadata
        if: always() # Run this step always, regardless of previous steps' outcomes
        run: echo "## Build ${{ github.run_id }}" >> $GITHUB_EVENT_NAME.log

      - name: Push changes
        if: always() && steps.semantic_release.outputs.published == 'true'
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Bump version"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
